apiVersion: v1
kind: Pod 
metadata:
  name: ros-talker
  labels:
    app: ros-talker
spec:
  containers:
  - name: ros-talker
    image: shahadarsh/ros-talker-listener:latest
    env:
    - name: ROS_HOSTNAME
      value: talker
    - name: ROS_MASTER_URI
      value: http://ros-core:11311
    args:
    - rosrun
    - roscpp_tutorials
    - talker
