apiVersion: v1
kind: Pod 
metadata:
  name: ros-listener
  labels:
    app: ros-talker-listener
spec:
  containers:
  - name: ros-listener
    image: shahadarsh/ros-talker-listener:latest
    env:
    - name: ROS_HOSTNAME
      value: listener
    - name: ROS_MASTER_URI
      value: http://ros-core:11311
    args:
    - rosrun
    - rospy_tutorials 
    - listener.py
